# Generated by Django 4.1.1 on 2022-09-11 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='firs_name',
            new_name='first_name',
        ),
    ]
